### ISSUE TITLE
Nativescript Webpack doesn't build

### ISSUE THREAD

**Issue by db3dev** [TeamMaestro/angular-native-seed#14]
When building a webpack bundle the current script removes necessary vendor files from the app directory.

**Comment by db3dev** [comment]
#15 resolves issues where webpack would not compile. Still the sample webpack project does not currently find the translation files.

**Comment by Dutchboy** [comment]
Hi!!! Strangely, it.still doesn't work... In the emulator it does, but when the apk installs on a device, it crashes... BTW, I've seen older tns / NG versions in the package.json ... Maybe that helps?

I do like your approach!
