### ISSUE TITLE
Serious update

### ISSUE THREAD

**Issue by Dutchboy** [TeamMaestro/angular-native-seed#17]
Hi guys....

I've just taken some time to update the package.json files to update it all to the latest tns 3 .... Any interest?
(and yes, it does work)

Problem is, I've never done a PR - I'm familiar to git though......

**Comment by jpinkster** [comment]
Here you go man! https://help.github.com/articles/creating-a-pull-request/

**Comment by sean-perkins** [comment]
@Dutchboy If you created a fork (and didn't git clone) you should be able to create a PR through Github's web interface. Simply changing the first drop down's source to the upstream (this seed).

**Comment by Dutchboy** [comment]
Well.... 😆 I guess I've done it!....
