### ISSUE TITLE
proxy.conf.json referenced in start script

### ISSUE THREAD

**Issue by hellofornow** [TeamMaestro/angular-native-seed#22]
start script explicitly references proxy.conf.json yet fresh clone has ".proxy.conf.json".

Was this intentional?

```
Proxy config file ~/angular-native-seed/proxy.conf.json does not exist.
```

**Comment by sean-perkins** [comment]
@hellofornow Good catch, unintentional. Should be `proxy.conf.json`. That'll be fixed in PR #19 soon.
