### ISSUE TITLE
Nativescript Webpack AOT Build Stopped Working

### ISSUE THREAD

**Issue by db3dev** [TeamMaestro/angular-native-seed#27]
Vanilla project no longer is building AOT. Initial errors are around package.json no longer being copied into the app directory.

**Comment by fourctv** [comment]
Still not working. Just got a fresh copy of the seed and `npm run build.tablet-ios-bundle` gives me these errors:
```
ERROR in /Users/jcarneiro/Downloads/angular-native-seed-master/nativescript/app/main.aot.ts (4,36): Cannot find module './app/app.module.ngfactory'.

ERROR in /Users/jcarneiro/Downloads/angular-native-seed-master/nativescript/app/main.ts (4,27): Cannot find module './app/app.module'.

ERROR in Could not resolve "/Users/jcarneiro/Downloads/angular-native-seed-master/nativescript/app/app/app.module" from "/Users/jcarneiro/Downloads/angular-native-seed-master/nativescript/app/app/app.module".

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app/app.module.ngfactory' in '/Users/jcarneiro/Downloads/angular-native-seed-master/nativescript/app'
 @ ./main.aot.ts 4:29-66
```

Running the app on emulator work fine, just the AOT build fails.

Environment: OSX 10.11.6
webpack:2.6.1
node: 7.4.0
tsc: 2.3.4
tns: 2.5.2

**Comment by db3dev** [comment]
@fourctv I don't think that error stops the application from launching in AOT. I'm going to close this issue because the original problem is solved. If you're still having AOT issues please open a new issue.
