### ISSUE TITLE
NativeScript theme doesn't seem to be working

### ISSUE THREAD

**Issue by sebawita** [TeamMaestro/angular-native-seed#30]
Out of the box the project imports one of the {N} themes: `@import 'nativescript-theme-core/css/core.light.css';`, however that doesn't seem to work

When I add a button like: `<Button text="TEST" class="btn btn-primary"></Button>` to the home component, the button appears without the expected style.

**Comment by fourctv** [comment]
You have to add this to your app.scss:
```
@import '~/nativescript-theme-core/css/core.light.css';
```

see `http://docs.nativescript.org/angular/ui/theme`

**Comment by sean-perkins** [comment]
<img width="394" alt="screen shot 2017-06-08 at 1 09 54 pm" src="https://user-images.githubusercontent.com/13732623/26941246-c9cbbf52-4c4b-11e7-8136-9cb2452c13cb.png">

Tested with PR #29. I'll merge that into master now. Try with that 👍

**Comment by sebawita** [comment]
It works like a charm 😃
