### ISSUE TITLE
Error compiling with webpack for Android

### ISSUE THREAD

**Issue by joshcomley** [TeamMaestro/angular-native-seed#38]
Hi again all,

I cloned the repo fresh today, ran both `npm i` commands and then tried to run `npm run build.phone-android-bundle` or `npm run phone-android-bundle` and get the following error:

	ERROR in Template parse errors:
	Can't bind to 'text' since it isn't a known property of 'Label'. ("<GridLayout rows="auto,auto">
		<Label class="h1 title"
			[ERROR ->][text]="'home.title' | translate"></Label>
	"): ng:///D:/Code/ngseed/nativescript/app/app/home/components/home/home.component.html@2:8
	Can't bind to 'text' since it isn't a known property of 'Label'. ("ome.title' | translate"></Label>
		<Label class="p description" textWrap="true" row="1"
			[ERROR ->][text]="'home.description' | translate"></Label>
	</GridLayout>
	"): ng:///D:/Code/ngseed/nativescript/app/app/home/components/home/home.component.html@4:8
	'GridLayout' is not a known element:
	1. If 'GridLayout' is an Angular component, then verify that it is part of this module.
	2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("[ERROR ->]<GridLayout rows="auto,auto">
		<Label class="h1 title"
			[text]="'home.title' | translate""): ng:///D:/Code/ngseed/nativescript/app/app/home/components/home/home.component.html@0:0

	ERROR in ./main.aot.ts
	Module not found: Error: Can't resolve './app/app.module.ngfactory' in 'D:\Code\ngseed\nativescript\app'
	 @ ./main.aot.ts 4:29-66

I am getting this on two separate machines.

Any thoughts?

**Comment by joshcomley** [comment]
`main.aot.ts` contains this import:

    import { AppModuleNgFactory } from './app/app.module.ngfactory';

But this file doesn't exist, I'm not 100% sure what magic makes this file but from my reading it looks like it is generated. Is this correct?

It also appears I should perhaps be using a specific TypeScript version. What version do  you guys use?

**Comment by fourctv** [comment]
I've had issues with 2.4.x, so I'm using 2.3.4 successfully.

**Comment by joshcomley** [comment]
What version of Node and NPM are you using?

**Comment by joshcomley** [comment]
OK after much fiddling I finally had a brainwave - I didn't realise that there were modules for home and about pages, and those modules don't contain:

    schemas: [
        NO_ERRORS_SCHEMA
    ]

Once I added this to both of those modules, it built.

**Comment by drosi94** [comment]
I have the same , i included

```
schemas: [
    NO_ERRORS_SCHEMA
]
```
to all .module.tns, but I got

`ERROR in Could not resolve "D:\projects\l2n\l2n-frontend\nativescript\app\app\app.module" from "D:\projects\l2n\l2n-frontend\nativescript\app\app\app.module".

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app/app.module.ngfactory' in 'D:\projects\l2n\l2n-frontend\nativescript\app'
 @ ./main.aot.ts 4:29-66
`

**Comment by drosi94** [comment]
I did the last update and i got this

4 import { AppModule } from './app/app.module';
                            ~~~~~~~~~~~~~~~~~~

```
app/main.ts(4,27): error TS2307: Cannot find module './app/app.module'.


Preparing project...
Processing node_modules failed. Error: spawn D:\projects\l2n\l2n-frontend\nativescript\platforms\android\gradlew.bat ENOENT
```

**Comment by db3dev** [comment]
Closing this issue. We restored the tns modules that include the no_errors_schema in the module.
