### ISSUE TITLE
[Discussion] What are the steps to update an existing project?

### ISSUE THREAD

**Issue by sebawita** [TeamMaestro/angular-native-seed#43]
I've been asked in my [article by Dinesh](https://www.nativescript.org/blog/code-sharing-between-web-and-mobile-with-angular-and-nativescript#comment-3439776732) about the required steps to update an existing `angular-native-seed` clone. 
I am not 100% sure what is the best way to approach it.
This looks like a good topic to have an open discussion about.

**Comment by sean-perkins** [comment]
1. Set the upstream for your git project to the seed's repository: `git remote add upstream https://github.com/TeamMaestro/angular-native-seed.git`

& the rest is stolen/repeat of what's mentioned in Nathan's seed.

2. `git fetch upstream` - This will fetch latest upstream.
3. `git merge upstream/master` - This will merge in upstream changes.
4. Handle any conflicts to get latest upstream into your app.
5. Continue building your app.

**Comment by db3dev** [comment]
I would recommend using `git rebase upstream/master` over `git merge`. This will keep all your development commits after the seed's changes.
