### ISSUE TITLE
Consistently getting error when compiling for android and ios

### ISSUE THREAD

**Issue by Xamlware** [TeamMaestro/angular-native-seed#47]
I cloned the project onto My MacBook pro and followed the instructions

On android:

> Project successfully created.
> Executing before-prepare hook from /Users/jbaird/Documents/development/test/nativescript/hooks/before-prepare/nativescript-dev-android-snapshot.js
> Executing before-prepare hook from /Users/jbaird/Documents/development/test/nativescript/hooks/before-prepare/nativescript-dev-sass.js
> Found peer node-sass
> No input file was found.
> 
> Unable to apply changes on device: 3300c7a83f28a385. Error is: SASS compiler failed with exit code 1.

On IOS..

> Project successfully created.
> Executing before-prepare hook from /Users/jbaird/Documents/development/test/nativescript/hooks/before-prepare/nativescript-dev-android-snapshot.js
> Executing before-prepare hook from /Users/jbaird/Documents/development/test/nativescript/hooks/before-prepare/nativescript-dev-sass.js
> Found peer node-sass
> No input file was found.
> 
> Unable to apply changes on device: f72f70777ff56844ed0217e01fe8d389ad058088. Error is: SASS compiler failed with exit code 1.

**Comment by sean-perkins** [comment]
Please refer to this issue: https://github.com/NativeScript/sample-Groceries/issues/267 and install `node-sass` globally.

`npm install -g node-sass`

Let me know if that resolves your issue.

**Comment by Xamlware** [comment]
Still getting same issue...

**Comment by sean-perkins** [comment]
I have re-cloned the project and had no trouble running both runtimes. The issue is definitely related to sass not being available on your machine.

When you run a blank NS project with the `nativescript-dev-sass` extension, do you also have this problem?

**Comment by Xamlware** [comment]
I created one and it built fine.  Error when trying to run on device.

**Comment by Xamlware** [comment]
I have SASS installed, I have node-sass installed and still the errors..

**Comment by londomloto** [comment]
have trying to create some .scss file and run tns run again?

**Comment by Xamlware** [comment]
It turned out to be permission on the platforms/ios and platforms/android folders.  I had to 

sudo chmod -R a+rwx 

for both directories to make it work.  I can't believe that this is not a problem that many experience and should be addressed in the read.me.

Thanks for the help you provided.

**Comment by vinayvnvv** [comment]
It is finding a at least one .scss or .sass file in `app`  folder. 
Just create >  `app.scss` file in `app` folder and rebuild the application.
