### ISSUE TITLE
No app.module.ts

### ISSUE THREAD

**Issue by Sharique-Hasan** [TeamMaestro/angular-native-seed#53]
there is no app.module.ts in this directory https://github.com/TeamMaestro/angular-native-seed/tree/master/nativescript/src and this file is referred in main.ts. 

Should I import the web's app.module.ts?

**Comment by sean-perkins** [comment]
The post install script creates a symlink between the `src/app` directory and `nativescript/app`. The `main.ts` file references `./app/app.module`, which will exist after you run `npm install` from the root project directory.

**Comment by Sharique-Hasan** [comment]
I am on windows. After npm install, postinstall runs but it exits by consoling "Configuring...". Nothing else

**Comment by Sharique-Hasan** [comment]
@sean-perkins Code doesn't enter in the if-check down below in the symlink.js file
```
// Root SymLink Code for Windows
if (process.argv.length > 2) {
    if (process.argv[2] === 'symlink') {
        createRootSymLink();
        console.log("Created Symlink");
    }
    return 0;
}

**Comment by sean-perkins** [comment]
@Sharique-Hasan Can you try running the script using the admin command prompt? We all use Macs in our office, so testing on a Windows machine will be difficult. 

The symlink script comes almost directly from Nathan Walker's implementation on the old seed: https://github.com/NathanWalker/angular-seed-advanced/blob/master/tools/install.js

I know users were able to successfully install his seed, so I am not completely sure on what's different between the implementations.
