### ISSUE TITLE
The parser encountered a bad or missing package name in the manifest..

### ISSUE THREAD

**Issue by makeAdance** [TeamMaestro/angular-native-seed#55]
Hi there.
I followed the Tutorial at 
https://www.nativescript.org/blog/code-sharing-between-web-and-mobile-with-angular-and-nativescript
and after I finished the part with the simple component I got the following error after executing npm run android:

Unable to apply changes on device: emulator-5554. Error is: The parser encountered a bad or missing package name in the manifest..
Executing after-watch hook from /Users/mad/Documents/Projects/express-seed/angular-native-seed/nativescript/hooks/after-watch/nativescript-dev-sass.js

In the first place the seed worked quite fine, but after that few changes there were the first problems.
Can someone please tell me what the problem could be and how I could solve it? Thanks.

**Comment by sean-perkins** [comment]
Can you please let me know if the solutions mentioned in this issue: https://github.com/TeamMaestro/angular-native-seed/issues/34 resolve your problem or if the problem persists?

**Comment by makeAdance** [comment]
I saw that entry but I did not unterstand the final solution out of the context..
What should I exactly try?
To create the NativeScript Project with the following template?
tns create ng-hello-world --template tns-template-hello-world-ng

**Comment by sean-perkins** [comment]
That comment was comparing a new project against the seed. 

I believe this is the temporary workaround: 

> If I go back to the original gradle file:
> \nativescript\App_Resources\Android\app.gradle
> 
> Change that from __PACKAGE__ to com.domain.project then I get npm run android.phone working every time.

Your original description doesn't mention if this is iOS/Android, so I am assuming it's Android based on the same build error.

**Comment by makeAdance** [comment]
It worked; thank you very much. :)

I assume the grey buttons on Android are normal? :)

**Comment by sean-perkins** [comment]
Yes, if you want them to look more like iOS, you can either create a separate stylesheet for android or apply the following button style in your  components' `tns.scss` file:

```
background-color: transparent;
border-color: transparent;
border-width: 1;
```

A good example of that can be found in this demo app: https://github.com/sean-perkins/nativescript-task-app (does not leverage the seed, just a regular NativeScript Angular app)

**Comment by makeAdance** [comment]
Thank`s for the support. Awesome. Thank you very much. :)
