### ISSUE TITLE
[(ngModel)]

### ISSUE THREAD

**Issue by makeAdance** [TeamMaestro/angular-native-seed#57]
What could be wrong if [(ngModel)] is not working in the seed?

Could it be because of the { N } or Angular Version?
How could I update the Version in the seed?
Should I just replace the version number in the package.json with a * ?

**Comment by sean-perkins** [comment]
Are you importing the `CommonModule` from `@angular/common`, which is required for that binding to work?

**Comment by makeAdance** [comment]
Where should it be imported?
In `app.module.tns.ts` ?

**Comment by makeAdance** [comment]
I thought that you just need to `import { FormsModule } from '@angular/forms';` for `[(ngModel)]`?
And that happens in the `shared.module.tns.ts` or not?

**Comment by sean-perkins** [comment]
You are correct, it does look like the `ngModel` binding is part of the FormsModule not the CommonModule. Although since the `SharedModule` does export the wrapped `NativeScriptFormsModule`, there shouldn't be any specific reason why `ngModel` is not working in your feature module, unless the `SharedModule` is not imported.

**Comment by makeAdance** [comment]
I think the SharedModule is imported correctly !?!

```
@NgModule({
    bootstrap: [
        AppComponent
    ],

    imports: [
        NativeScriptFormsModule,//Solved Problem

        
        NativeScriptModule,
        NativeScriptHttpModule,
        TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: (createTranslateLoader),
                deps: [Http]
            }
        }),
        ...SHARED_MODULES
    ],

    declarations: [
        AppComponent,
        RegisterComponent,
        LoginComponent,
        HomeComponent,
        DashboardComponent,
        ProfileComponent,
        NavbarComponent
    ],

    providers: [
        // Allows your {N} application to use lazy-loading
        { provide: NgModuleFactoryLoader, useClass: NSModuleFactoryLoader },
        AuthenticationService
    ],

    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AppModule { }
```
I imported the `NativeScriptFormsModule` separately and then it worked. But I am really interested why it`s not working with the SharedModule...

hm.
