### ISSUE TITLE
{N} and localhost 

### ISSUE THREAD

**Issue by makeAdance** [TeamMaestro/angular-native-seed#58]
How can I achieve that a http-request to `http://localhost:3000/example` is working?
I assume the problem occurs because you make no request to https !?!

After `npm run ios` and the request I get the following error:
```
App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1052:24: ERROR Error: Uncaught (in promise): Response with status: 200  for URL: null
```

I would like to know the best/correct approach to solve that problem. (both for ios/android)
Thanks.

**Comment by sean-perkins** [comment]
I would like to friendly remind you that the git issue tracking on this repository is focused solely on issues with the seed, the tooling tasks or dependency conflicts. 

This is not meant to and does not operate as a forum board for support on your NativeScript projects. 

Those appropriate channels are:
- [StackOverflow](https://stackoverflow.com)
- [NativeScript Forums](https://discourse.nativescript.org/)
- [NativeScript Slack](https://nativescriptcommunity.slack.com/messages/general/)
- [NativeScript Github Issues](https://github.com/NativeScript)

A simple Google search of your error would provide 61,000+ results on relative topics that point out the exact procedure to resolving this issue. 

The first Google result is this StackOverflow issue: https://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http

**Comment by makeAdance** [comment]
I understand. Sorry. I will keep that in mind for the future. Maybe you were to helpful; that`s why I kept asking. Of course I made a GoogleSearch and I found the side you referenced; but I thought that you might know it better. 
Never mind; I am sorry and I appreciate your help. Thanks for your time and the helpful links.
