### ISSUE TITLE
Question: How does the symlink exclude the web module?

### ISSUE THREAD

**Issue by snapnurse-joshuamatthews** [TeamMaestro/angular-native-seed#59]
I am attempting to drop this seeds technique of sharing code with the nativescript app into another project I am already working on. I added the symlink, but I am noticing that the same link in my app copies over all files, whereas in this seed the web module is left behind and only the .tns.module is copied over. Can you explain what mechanism accomplishes that?

**Comment by sean-perkins** [comment]
VSCode magic through the settings - https://github.com/TeamMaestro/angular-native-seed/blob/master/.vscode/settings.json#L11

The files are all there, just hidden to your IDE. Our gulp scripts copy out the correct file selectors on build.

**Comment by snapnurse-joshuamatthews** [comment]
Thanks!

**Comment by snapnurse-joshuamatthews** [comment]
@sean-perkins  Didn't want to open issue for this, just want to see if you know what is going on. 


As mentioned I dropped the nativescript folder into another project and setup all the code mirroring with symlink. Issue I am seeing is that in nativescript the build removes the scss files during the build, so they aren't there to be referenced at runtime. 

Nativescript docs seem to support that referencing the css if the right way. https://docs.nativescript.org/ui/theme#sass-usage

But I really need to reference the scss files from the web app because there is no css being generated there.

Any suggestions?

**Comment by sean-perkins** [comment]
Always use `.scss` file extensions for the stylesheets. Our gulp task replaces these out correctly on build.

https://github.com/TeamMaestro/angular-native-seed/blob/master/nativescript/gulpfile.js#L121

**Comment by snapnurse-joshuamatthews** [comment]
@sean-perkins  What I am seeing is that the gulp build compiles the source from nativescript/src to nativescript/app. And in nativescript/app both the css and the scss files are present. But then ultimately (and this is where things get a bit murky for me) the app ends up being compiled into the platforms/ios/nativescript folder within the xcode project. In that nativescript folder, the scss files are missing only the css remains, and I get errors when running the app that it cant find the scss file, which make sense because it isn't there. 

Are the scss files meant to make it all the way to the platforms/ios/nativescript folder? If they are then my problem is somewhere in that build process, if not then I'm not sure where they are supposed be be referenced from by the nativescript code. 

I appreciate the help on this!

**Comment by snapnurse-joshuamatthews** [comment]
@sean-perkins  Actually seems like the components themselves are being re-written in the app folder to target the css. Is that what is supposed to be happening? 

I think my issue is that the same is not happening for containers...

**Comment by snapnurse-joshuamatthews** [comment]
@sean-perkins  Actually seems the error is that only some of my components are being rewritten. I understand how its supposed to work now, just not sure why some of my folders are not being targeted.

**Comment by snapnurse-joshuamatthews** [comment]
@sean-perkins  Okay figured it out. Some of the components from the other project are not named with .component in the name, I see the selector needs that. Thanks for the help!
