### ISSUE TITLE
Fonts Folder 

### ISSUE THREAD

**Issue by makeAdance** [TeamMaestro/angular-native-seed#61]
I tried to include `FontAwesome` as described in http://docs.nativescript.org/ui/icon-fonts. In a 'normal‘ {N} project it`s working as expected, but in the seed project, I have some problems. (I think the *.tff file is not found.)
I know that I usually have to place the *.tff file in app/fonts; but in the structure of the seed nativescript/app/app I am not sure where to place it exactly. I do not get it working. 
Therefore I would like to know, where do I have to place the fonts folder in the seed?

**Comment by sean-perkins** [comment]
Anything in `nativescript/app` is removed on every build. Place the font in `nativescript/src/fonts/`.
