### ISSUE TITLE
Copying of Files and Folders should not happen always

### ISSUE THREAD

**Issue by mrelics** [TeamMaestro/angular-native-seed#63]
Hi ,

I am very new to this seed (and also nativescript and angular).

This seed main purpose is to built a hybrid web and Native app.I am aware of it.

My Problem is I have started the development first in nativescript. For that Views and folder structure will be different than the WEB.

Now the WEB Development I want to do it later.My Views for Web will be different.

I still want to reuse the SHARED code .So How I can restrict folders getting copied to WEB ? I can manually create the folder for WEB later.

This might be not an issue of this SEED.
Thanks
Manish Pandit

**Comment by sean-perkins** [comment]
Just create no-op files for the components you want "ignored". 

If you want a web-only component, create a template and component declaration that is empty.

example.component.tns.html
```html
<!-- noop -->
```

example.component.tns.ts
```ts
@Component({
    selector: 'example',
    template: './example.component.html'
})
export class ExampleComponent {}
```

Do the inverse if you want a {N} only component, that doesn't do anything for web build.

**Comment by mrelics** [comment]
Thanks a lot .
