### ISSUE TITLE
Navigation issues on Mobile

### ISSUE THREAD

**Issue by jdnichollsc** [TeamMaestro/angular-native-seed#68]
Hi guys,

I'm trying to modify the routes but the home modules doesn't load on iOS **(Only works on Web)**: 
https://github.com/proyecto26/nativescript-ionic-template

I want to have the routes like the following project: https://github.com/Especializa/nativescript-whatsapp-template/blob/master/app-routing.module.ts

Any help is really appreciated, Nicholls

**Comment by sean-perkins** [comment]
I believe for webpack NativeScript requires `app/` in the path. 

We do that inside our application:
```
 {
                path: 'dashboard',
                children: [
                    { path: '', pathMatch: 'full', redirectTo: 'user' },
                    {
                        path: 'user',
                        loadChildren:
                            'app/modules/+dashboard-user/dashboard-user.module#DashboardUserModule'
                    }
                ]
            },
```

**Comment by jdnichollsc** [comment]
yes, you're right! The home module was loaded using **app/** in the path, but the navigation only works on Web, on mobile doesn't work using `[nsRouterLink]="['/about']"`

**Comment by jdnichollsc** [comment]
It's an issue with the *nsRouterLink* using into ActionItems

**Comment by dcasbonne** [comment]
For me the solution was to add also "./" before "app". 
So I have :
```
loadChildren: './app/+about/about.module#AboutModule'
```
