### ISSUE TITLE
Ignoring all .js files, conflict with gulpfile.js file

### ISSUE THREAD

**Issue by jdnichollsc** [TeamMaestro/angular-native-seed#69]
Hi guys!
You're ignoring all .js files: https://github.com/TeamMaestro/angular-native-seed/blob/master/.gitignore#L36
And the nativescript/gulpfile.js is being ignored too

What do you think guys?

**Comment by jdnichollsc** [comment]
Please, accept the pull request to include the .js files required 👍

**Comment by sean-perkins** [comment]
Fixed with pr #70. Good work 👍
