### ISSUE TITLE
How did you test the application in the browser?

### ISSUE THREAD

**Issue by shaikhspear16** [TeamMaestro/angular-native-seed#71]
Not an issue. Query!

How did u do this?
https://camo.githubusercontent.com/e0adc7659a07e893159ded1f1c76377f573f2827/68747470733a2f2f692e6779617a6f2e636f6d2f31626134643362653762373333326365393162643637313564633735326438622e676966

**Comment by sean-perkins** [comment]
https://github.com/TeamMaestro/angular-native-seed/wiki/Seed-Commands

Mentions all the available commands for the project. Since this project is using the AngularCLI, you can use all the CLI commands just as you have before to run a web project.
