### ISSUE TITLE
No manifest found in <PATH>\nativescript\app\App_Resources\Android\AndroidManifest.xml

### ISSUE THREAD

**Issue by gordingin** [TeamMaestro/angular-native-seed#74]
I cloned the repo into d:\git\companyname\productname and after I npm install both folder, I try to run it with npm run android. 

I get this error 

No manifest found in d:\git\companyname\productname\nativescript\app\App_Resources\Android\AndroidManifest.xml

If I clone it into d:\git\companyname, follow the same process, it all works.

I do not think it like the subfolder.

Working in Windows 10

**Comment by sean-perkins** [comment]
Sub-folders should not effect the runtime of the apps. Please review popular Google searches regarding this issue, as 99% of the time it's related to out-dated NS versions or internet connectivity issues while installing packages.

https://discourse.nativescript.org/t/tns-build-error-sed-no-such-file-or-directory/1499/8
