### ISSUE TITLE
How To: Integrating rxjs/ngrx into the seed

### ISSUE THREAD

**Issue by sean-perkins** [TeamMaestro/angular-native-seed#8]
Create a Wiki page and video demonstrating how developers can integrate the `@ngrx` package, create an app state and manage a redux based application.

**Comment by jdnichollsc** [comment]
Hi man, thanks for this beautiful seed!
One question, What're the steps required to integrate ngrx? 👍

**Comment by sean-perkins** [comment]
Originally we had discussed integrating an ngrx implementation into the seed, but decided against it; as many low-level applications don't rely on it and we wanted to focus on leaving the seed as lean and focused around the AngularCLI and NativeScript Angular base project as possible. 

That being said, there is nothing special about this seed in terms of implementation. You can implement ngrx the same way that you would in any Angular application and it will work as expected.
