### ISSUE TITLE
Should sass compilation be happening out of the box?

### ISSUE THREAD

**Issue by BasyaLipman** [TeamMaestro/angular-native-seed#92]
I'm trying to use this seed as a base for my monorepo style app/website, and noticed that my sass files are not compiling into css in the src folder. 

Is this supposed to be happening?

Thanks!

**Comment by Tompote** [comment]
Hi !

Extension for sass files should be scss. You can check the gulpfile.js in charge of copying files in proper folders to understand how thing are working with this seed.

Hope this helped :).

**Comment by BasyaLipman** [comment]
@Tompote thanks. It looks like Webpack is actually responsible for it, and it does happen, but when running a build for mobile it'll just compile the scss files in the nativescript folder, not the web files in the src folder.
