### ISSUE TITLE
why stopped at "Xcode build...", when I run "npm run phone-is-bundle" command, but run "npm run phone-android-bundle" is working smoothly?

### ISSUE THREAD

**Issue by jianjunchang** [TeamMaestro/angular-native-seed#95]
Webpack compilation complete.
Project successfully prepared (iOS)
Executing after-prepare hook from /mypath/work/src/test/crossplatform/angular-native-seed/nativescript/hooks/after-prepare/nativescript-dev-android-snapshot.js
Executing after-prepare hook from /mypath/work/src/test/crossplatform/angular-native-seed/nativescript/hooks/after-prepare/nativescript-dev-sass.js
All SASS source files removed from app package
Executing after-prepare hook from /mypath/work/src/test/crossplatform/angular-native-seed/nativescript/hooks/after-prepare/nativescript-dev-webpack.js
Building project...
Xcode build...

any help is appreciated!

**Comment by fourctv** [comment]
have you recently upgraded XCode? You may need to agree to license changes or some other crap.

try to open XCode and see if you get a prompt for license agreement or for updating additional stuff.

I had the same issue last time I upgraded XCode.

**Comment by jianjunchang** [comment]
@fourctv thank you very much, yes, I have upgraded my Xcode recently,  I'll try your advice.

**Comment by jianjunchang** [comment]
@fourctv you are right ,now everything is ok, thinks again!
