### ISSUE TITLE
Is there a License on this project?

### ISSUE THREAD

**Issue by ylei-tsubame** [TeamMaestro/angular-native-seed#97]
Many thanks for creating this vital seed!

I could not find the license for this project; is there an existing one? If not, will the team be adding one in the near future?

**Comment by sean-perkins** [comment]
Please refer to the frameworks used for their respective licenses:
- https://github.com/NativeScript/NativeScript/blob/master/LICENSE
- https://github.com/angular/angular/blob/master/LICENSE

**Comment by ylei-tsubame** [comment]
Thanks a lot!
